# Generated by Django 4.2 on 2023-04-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasksmodel',
            table='tasks',
        ),
    ]
